SRCS := $(wildcard *.c) $(wildcard *.S)
OBJS := $(SRCS:.c=.o)
OBJS := $(OBJS:.S=.o)

%.o: %.c
	$(Q)$(CC) $(CFLAGS) -c $< -o $@

%.o: %.S
	$(Q)$(CC) $(CFLAGS) -c $< -o $@

OUTPUT = $(shell pwd | xargs basename)
